sharedDir: ".config"
outputDir: "lib"

mergeRules:
  ".gitignore": true
  ".husky/commit-msg": true
  ".npmignore": true

ignorePatterns:
  ".gitignore": [
    ".editorconfig",
    ".env",
    ".prettierignore",
    ".prettierrc",
    "/.husky/",
    "/.vscode/",
    "lib",
    "bin",
    "node_modules/",
  ]
  ".npmignore": [
    ".config",
    ".editorconfig",
    ".env",
    ".gitattributes",
    ".github",
    ".husky",
    ".prettierignore",
    ".prettierrc",
    ".sharedconfig.yml",
    ".vscode",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    "codecov.yml",
    "docs/",
    "example/",
    "media/",
    "node_modules/",
  ]

executableFiles: [
  ".husky/commit-msg",
]

scripts:
  "prepare:config": "node --experimental-specifier-resolution=node node_modules/.bin/base-shared-config"
  "prepare:husky": "husky install"
  "prepare": "npm-run-all prepare:*"
  "generate:changelog": "node --experimental-specifier-resolution=node node_modules/.bin/changelog generate --bump"
  "generate": "npm-run-all generate:*"
  "build": "node --experimental-specifier-resolution=node node_modules/.bin/standard-shared-config build"
  "release": "npm-run-all prepare build generate"

dependencies:
  - "changelog-guru": "3.x"
  - "husky": "7.x"
  - "npm-run-all"
  - "prettier"

package:
  exports: "./lib/index.js"
  manager: "npm"
  type: "module"
  types: "./lib/index.d.ts"
