sharedDir: ".config"
outputDir: "lib"

mergeRules:
  ".gitignore": true
  ".husky/commit-msg": true
  ".npmignore": true

ignorePatterns:
  ".gitignore": [
    ".env",
    "/.figma.yml",
    "/.husky/",
    "bin",
    "lib",
    "node_modules/",
  ]
  ".npmignore": [
    ".config",
    ".env",
    ".figma.yml",
    ".gitattributes",
    ".github",
    ".husky",
    ".sharedconfig.yml",
    "codecov.yml",
    "node_modules/",
  ]

executableFiles: [
  ".husky/commit-msg",
]

scripts:
  "build": "node --experimental-specifier-resolution=node node_modules/.bin/standard-shared-config build"
  "generate": "npm-run-all generate:*"
  "generate:changelog": "node --experimental-specifier-resolution=node node_modules/.bin/changelog generate --bump"
  "generate:media": "node --experimental-specifier-resolution=node node_modules/.bin/figma-portal extract -d media -p GitHub"
  "prepare": "npm-run-all prepare:*"
  "prepare:config": "node --experimental-specifier-resolution=node node_modules/.bin/base-shared-config"
  "prepare:husky": "husky install"
  "release": "npm-run-all prepare lint build generate"

dependencies:
  - "changelog-guru"
  - "figma-portal"
  - "husky": "8.x"
  - "npm-run-all"

package:
  exports: "./lib/index.js"
  manager: "npm"
  type: "module"
  types: "./lib/index.d.ts"
