sharedDir: ".config"
outputDir: "lib"

mergeRules:
  ".gitignore": true
  ".husky/commit-msg": true
  ".npmignore": true

ignorePatterns:
  ".gitignore": [
    ".env",
    "/.husky/",
    "bin",
    "lib",
    "node_modules/",
  ]
  ".npmignore": [
    ".config",
    ".env",
    ".gitattributes",
    ".github",
    ".husky",
    ".sharedconfig.yml",
    "codecov.yml",
    "node_modules/",
  ]

executableFiles: [
  ".husky/commit-msg",
]

scripts:
  "build": "standard-shared-config build"
  "generate": "npm-s generate:*"
  "generate:changelog": "changelog generate --bump"
  "prepare": "npm-s prepare:*"
  "prepare:config": "base-shared-config"
  "prepare:husky": "husky install"
  "release": "npm-s prepare lint build generate"

package:
  exports: "./lib/index.js"
  manager: "npm"
  type: "module"
  types: "./lib/index.d.ts"
